[build]
  # Specify the directory to build from
  base = "mall-screen"
  
  # Build command
  command = "npm run build"
  
  # Publish directory (where the built files will be)
  publish = "dist"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 