[build]
  publish = "mall-screen/dist"
  command = "cd mall-screen && npm install && npm run build"

[build.environment]
  VITE_API_URL = "https://sanhri-test-1.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 