[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://sanhri-test-1.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 