export const AdSampleData = [
  {
    id: "1",
    shopName: "Zara",
    shopNameHindi: "ज़ारा",
    shopNameMarathi: "ज़रा",
    address: "Ground floor, shop no. 4",
    addressHindi: "भूतल, दुकान नं. 4",
    addressMarathi: "तळमजला, दुकान क्रमांक ४",
    message: "Flat 20% Off on Men’s Clothing",
    messageHindi: "पुरुषों के कपड़ों पर 20% की छूट|",
    messageMarathi: "पुरुषांच्या कपड्यांवर २०% सूट.",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",
    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",
    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",
    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",
    priority: "High",
    adDuration: "20",
    adStartTime: "09:00 AM",
    adEndTime: "10:00 AM",
    adStartDate: "2025-06-25",
    adEndDate: "2025-10-19",
    adType: "Image",
    adSource: "/Ad/zara.jpg",

  },
  {
    id: "2",
    shopName: "KFC",
    shopNameHindi: "केएफ़सी",
    shopNameMarathi: "केएफसी",
    address: "1st floor, shop no. 1",
    addressHindi: "पहली मंज़िल, दुकान नं. 1",
    addressMarathi: "पहिला मजला, दुकान क्रमांक १",
    message: "Bucket Meals at ₹299",
    messageHindi: "बकेट मील्स ₹299 में",
    messageMarathi: "बकेट मील्स फक्त ₹२९९ मध्ये",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "High",
    adDuration: "20",
    adStartTime: "09:00 AM",
    adEndTime: "10:00 AM",
    adStartDate: "2025-06-25",
    adEndDate: "2025-07-1",
    adType: "Video",
    adSource: "/Ad/KFC.mp4",
  },
  {
    id: "3",
    shopName: "Adidas",
    shopNameHindi: "एडिडास",
    shopNameMarathi: "अ‍ॅडिडास",
    address: "2nd floor, shop no. 3",
    addressHindi: "दूसरी मंज़िल, दुकान नं. 3",
    addressMarathi: "दुसरा मजला, दुकान क्रमांक ३",
    message: "Exclusive 20% Off on Sportswear",
    messageHindi: "खेल परिधान पर विशेष 20% की छूट",
    messageMarathi: "स्पोर्ट्सवेअरवर खास २०% सूट",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "Medium",
    adDuration: "20",
    adStartTime: "10:00 AM",
    adEndTime: "11:00 AM",
    adStartDate: "2025-06-26",
    adEndDate: "2025-10-20",
    adType: "Image",
    adSource: "/Ad/adidas.jpg",
  },
  {
    id: "4",
    shopName: "Apple Store",
    shopNameHindi: "एप्पल स्टोर",
    shopNameMarathi: "ॲपल स्टोअर",
    address: "Ground floor, shop no. 2",
    addressHindi: "भूतल, दुकान नं. 2",
    addressMarathi: "तळमजला, दुकान क्रमांक २",
    message: "₹5000 Off on iPhone 14 & Free Accessories",
    messageHindi: "iPhone 14 पर ₹5000 की छूट और मुफ्त एक्सेसरीज़",
    messageMarathi: "iPhone 14 वर ₹५००० सूट आणि मोफत अ‍ॅक्सेसरी",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "High",
    adDuration: "20",
    adStartTime: "11:00 AM",
    adEndTime: "12:00 PM",
    adStartDate: "2025-06-27",
    adEndDate: "2025-10-25",
    adType: "Image",
    adSource: "/Ad/AppleStore.jpg",
  },
  {
    id: "5",
    shopName: "Croma",
    shopNameHindi: "क्रोमा",
    shopNameMarathi: "क्रोमा",
    address: "3rd floor, shop no. 5",
    addressHindi: "तीसरी मंज़िल, दुकान नं. 5",
    addressMarathi: "तिसरा मजला, दुकान क्रमांक ५",
    message: "Great Deals on Laptops & Smart TVs",
    messageHindi: "लैपटॉप और स्मार्ट टीवी पर शानदार ऑफर",
    messageMarathi: "लॅपटॉप व स्मार्ट टीव्हीवर अप्रतिम ऑफर्स",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "Medium",
    adDuration: "20",
    adStartTime: "01:00 PM",
    adEndTime: "02:00 PM",
    adStartDate: "2025-06-25",
    adEndDate: "2025-10-15",
    adType: "Image",
    adSource: "/Ad/Croma.jpg",
  },
  {
    id: "6",
    shopName: "Domino's Pizza",
    shopNameHindi: "डोमिनोज़ पिज़्ज़ा",
    shopNameMarathi: "डोमिनोज पिझ्झा",
    address: "2nd floor, shop no. 7",
    addressHindi: "दूसरी मंज़िल, दुकान नं. 7",
    addressMarathi: "दुसरा मजला, दुकान क्रमांक ७",
    message: "Buy 1 Pizza, Get 1 Freeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    messageHindi: "1 पिज्जा खरीदें, 1 मुफ्त पाएं....................................",
    messageMarathi: "१ पिझ्झा घ्या, १ मोफत मिळवा....................................",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "High",
    adDuration: "20",
    adStartTime: "12:00 PM",
    adEndTime: "01:00 PM",
    adStartDate: "2025-06-25",
    adEndDate: "2025-07-1",
    adType: "Video",
    adSource: "/Ad/Dominos.mp4",
  },
  {
    id: "7",
    shopName: "H&M",
    shopNameHindi: "एच एंड एम",
    shopNameMarathi: "एच अँड एम",
    address: "1st floor, shop no. 2",
    addressHindi: "पहली मंज़िल, दुकान नं. 2",
    addressMarathi: "पहिला मजला, दुकान क्रमांक २",
    message: "Buy 2 Get 1 Free on Summer Wear",
    messageHindi: "गर्मी के कपड़ों पर 2 खरीदें 1 मुफ्त पाएं",
    messageMarathi: "उन्हाळी कपड्यांवर २ खरेदी करा, १ मोफत मिळवा",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "Medium",
    adDuration: "20",
    adStartTime: "03:00 PM",
    adEndTime: "04:00 PM",
    adStartDate: "2025-06-28",
    adEndDate: "2025-10-22",
    adType: "Image",
    adSource: "/Ad/HM.jpg",
  },
  {
    id: "8",
    shopName: "Levi's",
    shopNameHindi: "लेवीज़",
    shopNameMarathi: "लेव्हिस",
    address: "4th floor, shop no. 1",
    addressHindi: "चौथी मंज़िल, दुकान नं. 1",
    addressMarathi: "चौथा मजला, दुकान क्रमांक १",
    message: "₹1000 Off on Jeans & Jackets",
    messageHindi: "जीन्स और जैकेट्स पर ₹1000 की छूट",
    messageMarathi: "जीन्स व जॅकेट्सवर ₹१००० सूट",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "Low",
    adDuration: "20",
    adStartTime: "02:00 PM",
    adEndTime: "03:00 PM",
    adStartDate: "2025-06-25",
    adEndDate: "2025-10-30",
    adType: "Image",
    adSource: "/Ad/Levis.jpg",
  },
  {
    id: "9",
    shopName: "McDonald's",
    shopNameHindi: "मैकडॉनल्ड्स",
    shopNameMarathi: "मॅकडोनाल्ड्स",
    address: "3rd floor, shop no. 2",
    addressHindi: "तीसरी मंज़िल, दुकान नं. 2",
    addressMarathi: "तिसरा मजला, दुकान क्रमांक २",
    message: "Combo Meals Starting at ₹199",
    messageHindi: "कॉम्बो मील्स ₹199 से शुरू",
    messageMarathi: "कॉम्बो मील्स ₹१९९ पासून सुरु",
    
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "Medium",
    adDuration: "30",
    adStartTime: "05:00 PM",
    adEndTime: "06:00 PM",
    adStartDate: "2025-06-25",
    adEndDate: "2025-10-19",
    adType: "Image",
    adSource: "/Ad/McDonalds.jpg",
  },
  {
    id: "10",
    shopName: "Nike",
    shopNameHindi: "नाइकी",
    shopNameMarathi: "नायकी",
    address: "2nd floor, shop no. 6",
    addressHindi: "दूसरी मंज़िल, दुकान नं. 6",
    addressMarathi: "दुसरा मजला, दुकान क्रमांक ६",
    message: "25% Off on Running Shoes & Activewear",
    messageHindi: "दौड़ने के जूते और एक्टिववेअर पर 25% की छूट",
    messageMarathi: "धावण्याचे शूज व अ‍ॅक्टिववेअरवर २५% सूट",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "High",
    adDuration: "21",
    adStartTime: "04:00 PM",
    adEndTime: "05:00 PM",
    adStartDate: "2025-06-26",
    adEndDate: "2025-10-21",
    adType: "Image",
    adSource: "/Ad/Nike.jpg",
  },
  {
    id: "11",
    shopName: "Puma",
    shopNameHindi: "प्यूमा",
    shopNameMarathi: "पुमा",
    address: "1st floor, shop no. 5",
    addressHindi: "पहली मंज़िल, दुकान नं. 5",
    addressMarathi: "पहिला मजला, दुकान क्रमांक ५",
    message: "20% Off on Sneakers & Sliders",
    messageHindi: "स्नीकर और स्लाइडर पर 20% की छूट",
    messageMarathi: "स्नीकर्स व स्लायडर्सवर २०% सूट",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "Low",
    adDuration: "17",
    adStartTime: "12:00 PM",
    adEndTime: "01:00 PM",
    adStartDate: "2025-06-27",
    adEndDate: "2025-10-17",
    adType: "Image",
    adSource: "/Ad/Puma.jpg",
  },
  {
    id: "12",
    shopName: "Samsung Experience Store",
    shopNameHindi: "सैमसंग एक्सपीरियंस स्टोर",
    shopNameMarathi: "सॅमसंग एक्सपीरियन्स स्टोअर",
    address: "Ground floor, shop no. 3",
    addressHindi: "भूतल, दुकान नं. 3",
    addressMarathi: "तळमजला, दुकान क्रमांक ३",
    message: "Smartwatch Combos – 20% Off",
    messageHindi: "स्मार्टवॉच कॉम्बोज़ पर 20% की छूट",
    messageMarathi: "स्मार्टवॉच कॉम्बोजवर २०% सूट",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "Medium",
    adDuration: "10",
    adStartTime: "11:00 AM",
    adEndTime: "12:00 PM",
    adStartDate: "2025-06-30",
    adEndDate: "2025-10-31",
    adType: "Image",
    adSource: "/Ad/SamsungExperienceStore.jpg",
  },
  {
    id: "13",
    shopName: "Titan",
    shopNameHindi: "टाइटन",
    shopNameMarathi: "टायटन",
    address: "5th floor, shop no. 2",
    addressHindi: "पाँचवी मंज़िल, दुकान नं. 2",
    addressMarathi: "पाचवा मजला, दुकान क्रमांक २",
    message: "Flat 20% Off on Men’s Watches",
    messageHindi: "पुरुषों की घड़ियों पर फ्लैट 20% की छूट",
    messageMarathi: "पुरुषांच्या घड्याळांवर फ्लॅट २०% सूट",
    messageSecond: "offer 2",
    messageSecondHindi: "ऑफ़र २",
    messageSecondMarathi: "ऑफर २",

    messageThird: "offer 3",
    messageThirdHindi: "ऑफ़र ३",
    messageThirdMarathi: "ऑफर ३",

    messageFourth: "offer 4",
    messageFourthHindi: "ऑफ़र ४",
    messageFourthMarathi: "ऑफर ४",

    messageFifth: "offer 5",
    messageFifthHindi: "ऑफ़र ५",
    messageFifthMarathi: "ऑफर ५",

    priority: "High",
    adDuration: "22",
    adStartTime: "01:00 PM",
    adEndTime: "02:00 PM",
    adStartDate: "2025-06-25",
    adEndDate: "2025-10-25",
    adType: "Image",
    adSource: "/Ad/Titan.jpg",
  },
];

export default AdSampleData;